services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API Port
      - "9001:9001"  # MinIO Console Port
    environment:
      MINIO_ROOT_USER: "minioadmin"       # Access Key (change this for security)
      MINIO_ROOT_PASSWORD: "minioadmin"  # Secret Key (change this for security)
    volumes:
      - minio-data:/data  # Persistent data storage
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"  # PostgreSQL Port
    environment:
      POSTGRES_USER: "postgres"       # Database username
      POSTGRES_PASSWORD: "password"  # Database password
      POSTGRES_DB: "upbank"      # Initial database name
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent database storage

volumes:
  minio-data:
    driver: local
  postgres-data:
    driver: local