client:
  base_url: https://api.up.com.au/api/v1/
  auth:
    type: bearer
    token: SOURCES__UPBANK__TOKEN
  paginator:
    type: json_link
    next_url_path: links.next

resource_defaults:
  endpoint:
    params:
      page[size]: 30
  write_disposition: merge
  primary_key: id
  data_selector: data

resources:
  - name: accounts
    endpoint:
      path: accounts
      params:
        since:
          type: incremental
          cursor_path: attributes.createdAt
          initial_value: 2019-08-03T00:00+11:00

  - name: transactions
    endpoint:
      path: transactions
      params:
        page[size]: 100
        since:
          type: incremental
          cursor_path: attributes.createdAt
          initial_value: 2025-01-01T00:00+11:00
